name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: whoan/docker-build-with-cache-action@v4
      with:
          image_tag: latest
          context: .
          dockerfile: tests.Dockerfile
          push_image_and_stages: true
          push_git_tag: false
          pull_image_and_stages: true
