name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: whoan/docker-build-with-cache-action@v4
    - name: Build the Docker image and run tests 
      run: docker build . --file tests.Dockerfile --tag tests:$(date +%s)
    
